services:
  rspec-2.6:
    build:
      context: .
      args:
        BASE_IMAGE: ruby:2.6
    volumes:
      - .:/app
  rspec-2.7:
    build:
      context: .
      args:
        BASE_IMAGE: ruby:2.7
    volumes:
      - .:/app
  rspec-3.0:
    build:
      context: .
      args:
        BASE_IMAGE: ruby:3.0
    volumes:
      - .:/app
